AllCops:
  TargetRubyVersion: 2.4

LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Exclude:
    - lib/dynamic_validation.rb
